services:
  user_service:
    image: ${OS:-openpanel/ubuntu}
    container_name: ${USERNAME}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    ports:
      - "${SSH_PORT}"
      - "${TTYD_PORT}"
    deploy:
      resources:
        limits:
          #pids: ${OS_PIDS:-100} # https://github.com/docker/cli/issues/5009
          cpus: "${OS_CPU:-0.5}"
          memory: "${OS_RAM:-0.5G}"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/openpanel/skeleton/motd:/etc/motd:ro          # SSH welcome message
      - /home/${CONTEXT}/mail/:/var/mail/                  # Mail storage
      - webserver_data:/etc/${WEB_SERVER}/sites-available/ # Nginx/Apache data
      - pg_data:/var/lib/postgresql/data                   # Postgres data
      - mysql_data:/var/lib/mysql                          # MySQL data
      - /home/${CONTEXT}/my.cnf:/root/.my.cnf              # mysql root pass - created/updated on mysql restart
      - html_data:/var/www/html/                           # Website files
      - /home/${CONTEXT}/sockets/:/var/run/                # All Sockets
      - /home/${CONTEXT}/php.ini/:/php/                    # php.ini files for containers
    networks:
      - www
      - db
    command: [ "tail", "-f", "/dev/null" ]

  busybox:
    image: busybox
    container_name: busybox          
    restart: always
    user: "${USER_ID:-0}"
    working_dir: /var/www/html
    deploy:
      resources:
        limits:
          cpus: "${BUSYBOX_CPU:-0.1}"
          memory: "${BUSYBOX_RAM:-0.1G}"   
    security_opt:
      - no-new-privileges:true
    volumes:
      - html_data:/var/www/html/

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    restart: always
    user: "${USER_ID:-0}"
    ports:
      - "${PROXY_HTTP_PORT:-${HTTP_PORT}}"
      - "${PROXY_HTTPS_PORT:-${HTTPS_PORT}}"
    working_dir: /var/www/html
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - webserver_data:/etc/nginx/conf.d
      - html_data:/var/www/html/                          # Website files     
      - /etc/openpanel/nginx/certs/:/etc/nginx/ssl/       # SSLs    
    deploy:
      resources:
        limits:
          cpus: "${NGINX_CPU:-0.5}"
          memory: "${NGINX_RAM:-0.5G}"   
    security_opt:
      - no-new-privileges:true
    networks:
      - www


  apache:
    image: httpd::${APACHE_VERSION:-latest}
    container_name: apache
    restart: always
    user: "${USER_ID:-0}"
    ports:
      - "${PROXY_HTTP_PORT:-${HTTP_PORT}}"
      - "${PROXY_HTTPS_PORT:-${HTTPS_PORT}}"
    working_dir: /var/www/html
    volumes:
      #- ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro         # Apache configuration
      - webserver_data:/usr/local/apache2/conf.d                   # Additional Apache configs
      - html_data:/usr/local/apache2/htdocs/                       # Website files
      - /etc/openpanel/nginx/certs/:/etc/apache2/ssl/              # SSL certificates
    deploy:
      resources:
        limits:
          cpus: "${APACHE_CPU:-0.5}"
          memory: "${APACHE_RAM:-0.5G}"
    security_opt:
      - no-new-privileges:true
    networks:
      - www

  varnish:
    image: varnish::${VARNISH_VERSION:-stable}
    container_name: varnish
    user: "${USER_ID:-0}"
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "${HTTP_PORT}"
      - "${HTTPS_PORT}"
    tmpfs:
      - /var/lib/varnish:exec
    deploy:
      resources:
        limits:
          cpus: "${VARNISH_CPU:-0.5}"
          memory: "${VARNISH_RAM:-0.5G}"       
    environment:
      - VARNISH_SIZE=${VARNISH_SIZE:-1G}
    command: "-p default_keep=300"
    depends_on:
      - "${WEB_SERVER:-nginx}"
    security_opt:
      - no-new-privileges:true
    networks:
      - www

      
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: mysql
    restart: always
    user: "${USER_ID:-0}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql                         # MySQL data
      - /home/${CONTEXT}/sockets/mysqld:/var/run/mysqld   # MySQL socket
      - /home/${CONTEXT}/my.cnf:/root/.my.cnf             # mysql root pass - created/updated on mysql restart
    deploy:
      resources:
        limits:
          cpus: "${MYSQL_CPU:-0.5}"
          memory: "${MYSQL_RAM:-0.5G}"
    networks:
      - db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost']
      interval: 1s
      timeout: 5s
      retries: 10

  mariadb:
    image: mariadb:${MYSQL_VERSION:-latest}
    container_name: mariadb
    restart: always
    user: "${USER_ID:-0}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql                         # MariaDB data
      - /home/${CONTEXT}/sockets/mysqld:/var/run/mysqld     # MariaDB socket
    deploy:
      resources:
        limits:
          cpus: "${MARIADB_CPU:-0.5}"
          memory: "${MARIADB_RAM:-0.5G}"
    security_opt:
      - no-new-privileges:true
    networks:
      - db
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost']
      interval: 1s
      timeout: 5s
      retries: 10

  phpmyadmin:
    container_name: phpmyadmin 
    depends_on:
      - "${MYSQL_TYPE:-mysql}"
    image: phpmyadmin #:5.2.2-fpm-alpine
    restart: always
    user: "${USER_ID:-0}"
    ports:
      - "${PMA_PORT}"
    deploy:
      resources:
        limits:
          cpus: "${PMA_CPU:-0.1}"
          memory: "${PMA_RAM:-0.1G}"                
    environment:
      PMA_HOST: ${MYSQL_TYPE:-mysql}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME:-600}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT:-512M}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-256M}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    networks:
      - db

  redis:
    image: redis:${REDIS_VERSION:-7.4.2-alpine}
    container_name: redis
    restart: unless-stopped
    user: "${USER_ID:-0}"
    volumes:
      - /home/${CONTEXT}/sockets/redis:/var/run/redis  # Redis socket
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPU:-0.1}"
          memory: "${REDIS_RAM-0.1G}" 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - www


  elasticsearch:
    image: elasticsearch:${ELASTICSEARH_VERSION:-7.16.1}
    container_name: elasticsearch
    restart: unless-stopped
    user: "${USER_ID:-0}"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /home/${CONTEXT}/sockets/elasticsearch:/var/run/elasticsearch
    deploy:
      resources:
        limits:
          cpus: "${ELASTICSEARCH_CPU:-0.5}"
          memory: "${ELASTICSEARCH_RAM-1G}" 
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - www


  memcached:
    image: memcached:${MEMCACHED_VERSION:-7.4.2-alpine}
    container_name: memcached
    restart: unless-stopped
    user: "${USER_ID:-0}"
    volumes:
      - /home/${CONTEXT}/sockets/memcached:/var/run/memcached  # Memcached socket
    deploy:
      resources:
        limits:
          cpus: "${MEMCACHED_CPU:-0.1}"
          memory: "${MEMCACHED_RAM-0.1G}" 
    command: [ "memcached", "-u", "root" ]
    healthcheck:    
      test: ["CMD", "memcached", "-h"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - www


  php-fpm-5.6:
    image: php:5.6-fpm
    container_name: php-fpm-5.6
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/5.6/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_5_6_CPU:-0.125}"
          memory: "${PHP_FPM_5_6_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-7.0:
    image: php:7.0-fpm
    container_name: php-fpm-7.0
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.0/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_7_0_CPU:-0.125}"
          memory: "${PHP_FPM_7_0_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-7.1:
    image: php:7.1-fpm
    container_name: php-fpm-7.1
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.1/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_7_1_CPU:-0.125}"
          memory: "${PHP_FPM_7_1_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-7.2:
    image: php:7.2-fpm
    container_name: php-fpm-7.2
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.2/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_7_2_CPU:-0.125}"
          memory: "${PHP_FPM_7_2_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-7.3:
    image: php:7.3-fpm
    container_name: php-fpm-7.3
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.3/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_7_3_CPU:-0.125}"
          memory: "${PHP_FPM_7_3_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-7.4:
    image: php:7.4-fpm
    container_name: php-fpm-7.4
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.4/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_7_4_CPU:-0.125}"
          memory: "${PHP_FPM_7_4_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-8.0:
    image: php:8.0-fpm
    container_name: php-fpm-8.0
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.0/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_8_0_CPU:-0.125}"
          memory: "${PHP_FPM_8_0_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-8.1:
    image: php:8.1-fpm
    container_name: php-fpm-8.1
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.1/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_8_1_CPU:-0.125}"
          memory: "${PHP_FPM_8_1_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-8.2:
    image: php:8.2-fpm
    container_name: php-fpm-8.2
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.2/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_8_2_CPU:-0.125}"
          memory: "${PHP_FPM_8_2_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-8.3:
    image: php:8.3-fpm
    container_name: php-fpm-8.3
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.3/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_8_3_CPU:-0.125}"
          memory: "${PHP_FPM_8_3_RAM:-0.25G}"
    networks:
      - www
      - db

  php-fpm-8.4:
    image: php:8.4-fpm
    container_name: php-fpm-8.4
    restart: always
    user: "${USER_ID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.4/:/usr/local/etc/php/
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_8_4_CPU:-0.125}"
          memory: "${PHP_FPM_8_4_RAM:-0.25G}"
    networks:
      - www
      - db


networks:
  default:
    driver: bridge
  www:
    driver: bridge
  db:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  html_data:
    driver: local
  webserver_data:
    driver: local
  pg_data:
    driver: local
