services:
  user_service:
    image: ${OS:-openpanel/ubuntu}
    container_name: ${USERNAME}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    ports:
      - "${SSH_PORT}"
      - "${TTYD_PORT}"
    deploy:
      resources:
        limits:
          cpus: "${OS_CPU:-0.5}"
          memory: "${OS_RAM:-0.5G}"
    volumes:
      - /etc/openpanel/skeleton/motd:/etc/motd:ro         # SSH welcome message
      - /home/${CONTEXT}/mail/:/var/mail/                 # Mail storage
      - webserver_data:/etc/${path}/sites-available/      # Nginx/Apache data
      - pg_data:/var/lib/postgresql/data                  # Postgres data
      - mysql_data:/var/lib/mysql                         # MySQL data      
      - html_data:/var/www/html/                          # Website files
      - /home/${CONTEXT}/sockets/:/var/run/               # All Sockets
    networks:
      - default
    command: [ "tail", "-f", "/dev/null" ]
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    user: "${UID:-0}"
    ports:
      - "${HTTP_PORT}"
      - "${HTTPS_PORT}"
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      - webserver_data:/etc/${path}/sites-available/
      - html_data:/var/www/html/                          # Website files     
    deploy:
      resources:
        limits:
          cpus: "${NGINX_CPU:-0.5}"
          memory: "${NGINX_RAM:-0.5G}"   
    networks:
      - default


  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "${HTTP_PORT}"
      - "${HTTPS_PORT}"
    tmpfs:
      - /var/lib/varnish:exec
    deploy:
      resources:
        limits:
          cpus: "${VARNISH_CPU:-0.5}"
          memory: "${VARNISH_RAM:-0.5G}"       
    environment:
      - VARNISH_SIZE=${VARNISH_SIZE:-1G}
    command: "-p default_keep=300"
    depends_on:
      - "${WEB_SERVER:-nginx}"


  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: mysql
    restart: always
    user: "${UID:-0}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql                         # MySQL data
      - /home/${CONTEXT}/sockets/mysqld:/var/run/mysqld   # MySQL socket
    deploy:
      resources:
        limits:
          cpus: "${MYSQL_CPU:-0.5}"
          memory: "${MYSQL_RAM:-0.5G}"
    networks:
      - default
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost']
      interval: 1s
      timeout: 5s
      retries: 10
    command: >
      sh -c "echo 'user=root' >> /etc/my.cnf &&
             echo 'password=${MYSQL_ROOT_PASSWORD:-rootpassword}' >> /etc/my.cnf &&
             cat /etc/my.cnf &&
             exec docker-entrypoint.sh mysqld"

  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mariadb
    restart: always
    user: "${UID:-0}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql                         # MariaDB data
      - /home/${CONTEXT}/sockets/mysqld:/var/run/mysqld     # MariaDB socket
    deploy:
      resources:
        limits:
          cpus: "${MARIADB_CPU:-0.5}"
          memory: "${MARIADB_RAM:-0.5G}"
    networks:
      - default
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost']
      interval: 1s
      timeout: 5s
      retries: 10
    command: >
      sh -c "echo 'user=root' >> /etc/my.cnf &&
             echo 'password=${MYSQL_ROOT_PASSWORD:-rootpassword}' >> /etc/my.cnf &&
             cat /etc/my.cnf &&
             exec docker-entrypoint.sh mysqld"

  phpmyadmin:
    container_name: phpmyadmin 
    depends_on:
      - "${MYSQL_TYPE:-mysql}"
    image: phpmyadmin #:5.2.2-fpm-alpine
    restart: always
    user: "${UID:-0}"
    ports:
      - "${PMA_PORT}"
    deploy:
      resources:
        limits:
          cpus: "${PMA_CPU:-0.1}"
          memory: "${PMA_RAM:-0.1G}"                
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION:-7.4.2-alpine}
    container_name: redis
    restart: unless-stopped
    user: "${UID:-0}"
    volumes:
      - /home/${CONTEXT}/sockets/redis:/var/run/redis  # Redis socket
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPU:-0.1}"
          memory: "${REDIS_RAM-0.1G}" 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - default

  memcached:
    image: memcached:${MEMCACHED_VERSION:-7.4.2-alpine}
    container_name: memcached
    restart: unless-stopped
    user: "${UID:-0}"
    volumes:
      - /home/${CONTEXT}/sockets/memcached:/var/run/memcached  # Memcached socket
    deploy:
      resources:
        limits:
          cpus: "${MEMCACHED_CPU:-0.1}"
          memory: "${MEMCACHED_RAM-0.1G}" 
    command: [ "memcached", "-u", "root" ]
    healthcheck:    
      test: ["CMD", "memcached", "-h"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - default



  php-fpm-5.6:
    image: php:5.6-fpm
    container_name: php-fpm-5.6
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/5.6.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_56_CPU:-0.125}"
          memory: "${PHP_56_RAM:-0.25G}"
    networks:
      - default

  php-fpm-7.0:
    image: php:7.0-fpm
    container_name: php-fpm-7.0
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.0.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_70_CPU:-0.125}"
          memory: "${PHP_70_RAM:-0.25G}"
    networks:
      - default

  php-fpm-7.1:
    image: php:7.1-fpm
    container_name: php-fpm-7.1
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.1.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_71_CPU:-0.125}"
          memory: "${PHP_71_RAM:-0.25G}"
    networks:
      - default

  php-fpm-7.2:
    image: php:7.2-fpm
    container_name: php-fpm-7.2
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.2.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_72_CPU:-0.125}"
          memory: "${PHP_72_RAM:-0.25G}"
    networks:
      - default

  php-fpm-7.3:
    image: php:7.3-fpm
    container_name: php-fpm-7.3
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.3.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_73_CPU:-0.125}"
          memory: "${PHP_73_RAM:-0.25G}"
    networks:
      - default

  php-fpm-7.4:
    image: php:7.4-fpm
    container_name: php-fpm-7.4
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/7.4.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_74_CPU:-0.125}"
          memory: "${PHP_74_RAM:-0.25G}"
    networks:
      - default

  php-fpm-8.0:
    image: php:8.0-fpm
    container_name: php-fpm-8.0
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.0.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_80_CPU:-0.125}"
          memory: "${PHP_80_RAM:-0.25G}"
    networks:
      - default

  php-fpm-8.1:
    image: php:8.1-fpm
    container_name: php-fpm-8.1
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.1.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_81_CPU:-0.125}"
          memory: "${PHP_81_RAM:-0.25G}"
    networks:
      - default

  php-fpm-8.2:
    image: php:8.2-fpm
    container_name: php-fpm-8.2
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.2.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_82_CPU:-0.125}"
          memory: "${PHP_82_RAM:-0.25G}"
    networks:
      - default

  php-fpm-8.3:
    image: php:8.3-fpm
    container_name: php-fpm-8.3
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.3.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_83_CPU:-0.125}"
          memory: "${PHP_83_RAM:-0.25G}"
    networks:
      - default

  php-fpm-8.4:
    image: php:8.4-fpm
    container_name: php-fpm-8.4
    restart: always
    user: "${UID:-0}"
    volumes:
      - html_data:/var/www/html/
      - /home/${CONTEXT}/php.ini/8.4.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_84_CPU:-0.125}"
          memory: "${PHP_84_RAM:-0.25G}"
    networks:
      - default



networks:
  default:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  html_data:
    driver: local
  webserver_data:
    driver: local
  pg_data:
    driver: local
