include:
  - ubuntu.yaml
  - mysql.yaml
  - memcached.yaml
  - redis.yaml
  - nginx.yaml
  #- apache.yaml
  #- mariadb.yaml  
  #- postgres.yaml
  #- php1, php2..
  #- pgadmin.yaml
  - phpmyadmin.yaml

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  html_data:
    driver: local
  webserver_data:
    driver: local
  pg_data:
    driver: local
