services:
  memcached:
    image: memcached:${MEMCACHED_VERSION:-7.4.2-alpine}
    container_name: memcached
    restart: unless-stopped
    user: "${UID:-0}"
    volumes:
      - /home/${CONTEXT}/sockets/memcached:/var/run/memcached  # Memcached socket
    deploy:
      resources:
        limits:
          cpus: "${MEMCACHED_CPU:-0.1}"
          memory: "${MEMCACHED_RAM-0.1G}" 
    command: [ "memcached", "-u", "root" ]
    healthcheck:    
      test: ["CMD", "memcached", "-h"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - default

networks:
  default:
    driver: bridge
