services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    user: "${UID:-0}"
    ports:
      - "${HTTP_PORT}"
      - "${HTTPS_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - webserver_data:/etc/${path}/sites-enabled/
      - html_data:/var/www/html/                          # Website files     
     deploy:
      resources:
        limits:
          cpus: "${NGINX_CPU:-0.5}"
          memory: "${NGINX_RAM:-0.5G}"   
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  html_data:
    driver: local
  webserver_data:
    driver: local
      
