services:
  phpmyadmin:
    container_name: phpmyadmin 
    depends_on:
      - mysql
    image: phpmyadmin #:5.2.2-fpm-alpine
    restart: always
    user: "${UID:-0}"
    ports:
      - "${PMA_PORT}"
    deploy:
      resources:
        limits:
          cpus: "${PMA_CPU:-0.1}"
          memory: "${PMA_RAM:-0.1G}"                
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    networks:
      - default

networks:
  default:
    driver: bridge
