services:
  redis:
    image: redis:${REDIS_VERSION:-7.4.2-alpine}
    container_name: redis
    restart: unless-stopped
    user: "${UID:-0}"
    volumes:
      - /home/${CONTEXT}/sockets/redis:/var/run/redis  # Redis socket
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPU:-0.1}"
          memory: "${REDIS_RAM-0.1G}" 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - default

networks:
  default:
    driver: bridge
