services:
  # Database for OpenPanel users, plans, websites and domains
  openpanel_mysql:
    image: mysql/mysql-server
    container_name: openpanel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - openadmin_mysql:/var/lib/mysql
      - /etc/openpanel/:/etc/openpanel/
      - /root/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    mem_limit: 0.5g
    cpus: 1.0
    oom_kill_disable: true

  # Malware Scanner used from user panel
  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    volumes:
      - /home:/home
      - ./clamav-db:/var/lib/clamav
    restart: unless-stopped
    environment:
      - CLAMD_STARTUP_DELAY=30
    mem_limit: 1g
    cpus: 1.0

  # OpenPanel service running on port 2083
  openpanel:
    image: openpanel/openpanel
    container_name: openpanel
    depends_on:
      - openpanel_mysql
      #- clamav
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /etc/nginx/sites-available/:/etc/nginx/sites-available/
      - /etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - /etc/bind:/etc/bind
      - /lib/modules:/lib/modules:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
      - /home:/home
      - /usr/local/admin:/usr/local/admin
      - /usr/local/admin/scripts:/usr/local/admin/scripts
      - /var/log:/var/log
      - /etc/ufw:/etc/ufw
      - /var/lib/csf/:/var/lib/csf/
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/my.cnf:/etc/my.cnf
      - /etc/openpanel/:/etc/openpanel/
      - /var/run/docker.sock:/var/run/docker.sock
      - openadmin_mysql:/var/lib/mysql
      - /usr/bin/docker:/usr/bin/docker
      - /root/:/root/
      #  https://dev.openpanel.com/customize.html#Custom-Code
      - /etc/openpanel/openpanel/custom_code/:/usr/local/panel/templates/custom_code/
      - /etc/openpanel/openpanel/custom_code/custom.css:/usr/local/panel/static/css/custom.css
      - /etc/openpanel/openpanel/custom_code/custom.js:/usr/local/panel/static/js/custom.js
      - /etc/openpanel/openpanel/conf/knowledge_base_articles.json:/etc/openpanel/openpanel/conf/knowledge_base_articles.json
      # localization
      - /etc/openpanel/openpanel/translations/:/etc/openpanel/openpanel/translations/
      # emails
      - /usr/local/mail/openmail/:/usr/local/mail/openmail/
    network_mode: host
    mem_limit: 1g
    cpus: 1.0
    restart: always
    privileged: true
    userns_mode: host

  # Webserver from 1.0.0
  caddy:
    image: caddy:latest
    container_name: caddy
    network_mode: "host"
    volumes:
      - /etc/openpanel/caddy/Caddyfile:/etc/caddy/Caddyfile                    # Caddy config
      - /etc/openpanel/caddy/sites:/etc/caddy/sites                            # Site configurations (optional, modular sites)
      - /etc/openpanel/caddy/ssl:/data/caddy/certificates                      # Custom SSL certificates
      - /etc/openpanel/caddy/logs:/var/log/caddy                               # Caddy logs
      - /etc/hosts:/etc/hosts                                                  # To maintain host configurations
      - /home:/home                                                            # user files
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0
    oom_kill_disable: true
    
  # SSL status and renewals
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    network_mode: "host"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt                                         # Let's Encrypt certificates are stored here
      - /var/lib/letsencrypt:/var/lib/letsencrypt                                 # Working directory for Certbot container
      - /etc/nginx/sites-available:/etc/nginx/sites-available                     # Access to Nginx config for authentication challenges
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled                         # Enabled sites for reloading after cert issuance
      - /var/log/letsencrypt/letsencrypt.log:/var/log/letsencrypt/letsencrypt.log # for troubleshooting
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; nginx -s reload; done'
    restart: unless-stopped
    mem_limit: 0.1g
    cpus: 0.1
    oom_kill_disable: true

  # DNS
  bind9:
    container_name: openpanel_dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /etc/bind/:/etc/bind/
    restart: unless-stopped
    mem_limit: 0.1g
    cpus: 0.1
    oom_kill_disable: true

  # FTP
  ftp_env_generator:
    image: alpine:latest
    container_name: ftp_env_generator
    volumes:
      - /etc/openpanel/ftp/:/etc/openpanel/ftp/
      - /usr/local/admin/scripts/ftp/users:/usr/local/admin/scripts/ftp/users
    entrypoint: /bin/sh -c "/usr/local/admin/scripts/ftp/users"
    restart: "no"  # only run once

  openadmin_ftp:
    build:
      context: /etc/openpanel/ftp/    
    container_name: openadmin_ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - /home/:/home/
      - /etc/openpanel/ftp/vsftpd.conf:/etc/vsftpd/vsftpd.conf
      - /etc/openpanel/ftp/start_vsftpd.sh:/bin/start_vsftpd.sh
      - /etc/openpanel/ftp/vsftpd.chroot_list:/etc/vsftpd.chroot_list
      - /etc/openpanel/users/:/etc/openpanel/ftp/users/
    depends_on:
      - ftp_env_generator
    env_file:
      - /etc/openpanel/ftp/all.users
    mem_limit: 0.5g
    cpus: 0.5



# make the mysql data persistent
volumes:
  openadmin_mysql:
