services:
  # Database for OpenPanel users, plans, websites and domains
  openpanel_mysql:
    image: mysql/mysql-server
    container_name: openpanel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - /etc/openpanel/:/etc/openpanel/
      - /root/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    mem_limit: ${MYSQL_RAM}
    cpus: ${MYSQL_CPUS}
    oom_kill_disable: true
    networks:
      - openpanel_network
    

  # Malware Scanner used from user panel
  clamav:
    image: clamav/clamav:${CLAMAV_VERSION}
    container_name: clamav
    volumes:
      - /home:/home
      - ./clamav-db:/var/lib/clamav
    restart: unless-stopped
    network_mode: ${CLAMAV_DB_AUTOUPDATE} # needed to update db daily
    environment:
      - CLAMD_STARTUP_DELAY=${CLAMD_STARTUP_DELAY}
    mem_limit: ${CLAMAV_RAM}
    cpus: ${CLAMAV_CPUS}

# used by panel ui to store user sessions and counters
  openpanel_redis:
    image: redis:latest
    container_name: openpanel_redis
    #command: /bin/bash -c "mkdir -p /tmp/redis && chmod 770 /tmp/redis && chown 999:999 /tmp/redis && redis-server --unixsocket /tmp/redis/redis.sock --unixsocketperm 770 --port 0"
    command: ["redis-server", "--unixsocket", "/tmp/redis/redis.sock", "--unixsocketperm", "770"]
    volumes:
      - ${REDIS_SOCKET}:/tmp/redis/
    mem_limit: ${REDIS_RAM}
    cpus: ${REDIS_CPUS}
    restart: always
    networks:
      - openpanel_network

  # OpenPanel service running on port 2083
  openpanel:
    image: openpanel/openpanel:${VERSION}
    container_name: openpanel
    depends_on:
      - openpanel_mysql
      - openpanel_redis
      #- clamav
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "${PORT}:2083/tcp"
    volumes:
      - /etc/bind:/etc/bind
      - /lib/modules:/lib/modules:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
      - /home:/home
      - /usr/local/admin:/usr/local/admin
      - /usr/local/bin/opencli:/usr/local/bin/opencli
      - /usr/local/opencli:/usr/local/opencli
      - /var/log:/var/log
      - /etc/ufw:/etc/ufw
      - /var/lib/csf/:/var/lib/csf/
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/openpanel/mysql/container_my.cnf:/etc/my.cnf
      - /etc/openpanel/:/etc/openpanel/
      - /var/run/docker.sock:/var/run/docker.sock
      - mysql:/var/lib/mysql
      - /usr/bin/docker:/usr/bin/docker
      - /root/:/root/
      - ${REDIS_SOCKET}:/tmp/redis/
      #  https://dev.openpanel.com/customize.html#Custom-Code
      - /etc/openpanel/openpanel/custom_code/:/usr/local/panel/templates/custom_code/
      - /etc/openpanel/openpanel/custom_code/custom.css:/usr/local/panel/static/css/custom.css
      - /etc/openpanel/openpanel/custom_code/custom.js:/usr/local/panel/static/js/custom.js
      - /etc/openpanel/openpanel/conf/knowledge_base_articles.json:/etc/openpanel/openpanel/conf/knowledge_base_articles.json
      # localization
      - /etc/openpanel/openpanel/translations/:/etc/openpanel/openpanel/translations/
      # emails
      - /usr/local/mail/openmail/:/usr/local/mail/openmail/
    restart: always
    privileged: true
    networks:
      - openpanel_network
    #OFF FOR USER ROOT#userns_mode: host
        
  # Webserver from 1.0.0
  caddy:
    image: ${CADDY_IMAGE}
    container_name: caddy
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/openpanel/caddy/Caddyfile:/etc/caddy/Caddyfile                           # Caddy config
      - /etc/openpanel/caddy/ssl:/data/caddy/certificates                             # Custom SSL certificates
      - /etc/openpanel/caddy/:/etc/openpanel/caddy/                                   # domain files, templates 
      - /etc/openpanel/caddy/coraza_rules.conf:/etc/openpanel/caddy/coraza_rules.conf # default rules
      - /var/log/caddy/:/var/log/caddy/
    restart: unless-stopped
    mem_limit: ${CADDY_RAM}
    cpus: ${CADDY_CPUS}
    oom_kill_disable: true
    network_mode: host

  # DNS
  bind9:
    container_name: openpanel_dns
    image: ubuntu/bind9:${BIND9_VERSION}
    environment:
      - BIND9_USER=root
      - TZ=${BIND_TIMEZONE}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /etc/bind/:/etc/bind/
    restart: unless-stopped
    mem_limit: ${BIND9_RAM}
    cpus: ${BIND9_CPUS}
    oom_kill_disable: true
    networks:
      - openpanel_network

  # FTP
  ftp_env_generator:
    image: alpine:latest
    container_name: ftp_env_generator
    volumes:
      - /etc/openpanel/ftp/:/etc/openpanel/ftp/
      - /usr/local/admin/scripts/ftp/users:/usr/local/admin/scripts/ftp/users
    entrypoint: /bin/sh -c "/usr/local/admin/scripts/ftp/users"
    restart: "no"  # only run once
    networks:
      - openpanel_network

  openadmin_ftp:
    build:
      context: /etc/openpanel/ftp/    
    container_name: openadmin_ftp
    restart: always
    ports:
      - "21:21"
      - "${FTP_PORT_RANGE}:21000-21010"
    volumes:
      - /home/:/home/
      - /etc/openpanel/ftp/vsftpd.conf:/etc/vsftpd/vsftpd.conf
      - /etc/openpanel/ftp/start_vsftpd.sh:/bin/start_vsftpd.sh
      - /etc/openpanel/ftp/vsftpd.chroot_list:/etc/vsftpd.chroot_list
      - /etc/openpanel/users/:/etc/openpanel/ftp/users/
    depends_on:
      - ftp_env_generator
    env_file:
      - /etc/openpanel/ftp/all.users
    mem_limit: ${FTP_RAM}
    cpus: ${FTP_CPUS}
    networks:
      - openpanel_network


# make the mysql data persistent
volumes:
  mysql:


# define custom network
networks:
  openpanel_network:
    driver: bridge
