services:
  # Database for OpenPanel users, plans, websites and domains
  openpanel_mysql:
    image: mysql/mysql-server
    container_name: openpanel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - openadmin_mysql:/var/lib/mysql
      - /etc/openpanel/:/etc/openpanel/
      - /etc/openpanel/docker/compose/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    mem_limit: 0.5g
    cpus: 1.0
    oom_kill_disable: true

  # OpenPanel service running on port 2083
  openpanel:
    image: openpanel/openpanel
    container_name: openpanel
    depends_on:
      - openpanel_mysql
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /etc/nginx/sites-available/:/etc/nginx/sites-available/
      - /etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - /etc/bind:/etc/bind
      - /lib/modules:/lib/modules:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
      - /home:/home
      - /usr/local/admin:/usr/local/admin
      - /usr/local/admin/scripts:/usr/local/admin/scripts
      - /var/log:/var/log
      - /etc/ufw:/etc/ufw
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/my.cnf:/etc/my.cnf
      - /etc/openpanel/:/etc/openpanel/
      - /var/run/docker.sock:/var/run/docker.sock
      - openadmin_mysql:/var/lib/mysql
      - /usr/bin/docker:/usr/bin/docker
      - /root/:/root/
    network_mode: host
    mem_limit: 1g
    cpus: 1.0
    restart: always
    privileged: true

  # Webserver from 0.2.5+
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
        - /etc/openpanel/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/openpanel/nginx/vhosts/default.conf:/etc/nginx/sites-available/default
        - /etc/openpanel/nginx/vhosts/default.conf:/etc/nginx/sites-enabled/default
        - /etc/openpanel/nginx/vhosts/default.conf:/etc/nginx/conf.d/default.conf 
        - /etc/openpanel/nginx/vhosts/openpanel_proxy.conf:/etc/openpanel/nginx/vhosts/openpanel_proxy.conf
        - /etc/nginx/sites-available/:/etc/nginx/sites-available/
        - /etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
        - /etc/openpanel/nginx/error_pages/snippets/:/etc/nginx/snippets/
        - /etc/openpanel/nginx/error_pages/:/srv/http/default/
        - /var/log/nginx/:/var/log/nginx/
        - /etc/letsencrypt/:/etc/letsencrypt/
        - /etc/openpanel/openpanel/core/users/:/etc/openpanel/openpanel/core/users/
        - /etc/hosts:/etc/hosts
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0
    oom_kill_disable: true
    
  # SSL status and renewals
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    network_mode: "host"  # Use host network for direct access to web servers
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt                    # Let's Encrypt certificates
      - /var/lib/letsencrypt:/var/lib/letsencrypt            # Working directory for Certbot
      - /etc/nginx/sites-available:/etc/nginx/sites-available # Access to Nginx config for authentication challenges
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled    # Enabled sites for reloading after cert issuance
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; nginx -s reload; done'
    restart: unless-stopped
    mem_limit: 0.1g
    cpus: 0.1
    oom_kill_disable: true

  # DNS
  bind9:
    container_name: openpanel_dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /etc/bind/:/etc/bind/
    restart: unless-stopped
    mem_limit: 0.1g
    cpus: 0.1
    oom_kill_disable: true

  #mailserver:
  #  image: ghcr.io/docker-mailserver/docker-mailserver:latest
  #  container_name: openadmin_mailserver
  #  hostname: mail.openpanel.site
  #  env_file: mailserver.env
  #  ports:
  #    - "25:25"
  #    - "143:143"
  #    - "465:465"
  #    - "587:587"
  #    - "993:993"
  #  volumes:
  #    - ./docker-data/dms/mail-data/:/var/mail/
  #    - ./docker-data/dms/mail-state/:/var/mail-state/
  #    - ./docker-data/dms/mail-logs/:/var/log/mail/
  #    - ./docker-data/dms/config/:/tmp/docker-mailserver/
  #    - /etc/localtime:/etc/localtime:ro
  #  restart: always
  #  stop_grace_period: 1m
  #  healthcheck:
  #    test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
  #    timeout: 3s
  #    retries: 0
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 1g
  #        cpus: '1.0'
  #  networks:
  #    - openadmin_mail_network

  #roundcube:
  #  image: roundcube/roundcubemail
  #  container_name: openadmin_roundcube
  #  restart: always
  #  environment:
  #    - ROUNDCUBEMAIL_DEFAULT_HOST=openadmin_mailserver
  #    - ROUNDCUBEMAIL_SMTP_SERVER=openadmin_mailserver
  #  ports:
  #    - "8080:80"
  #  networks:
  #    - openadmin_mail_network
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 1g
  #        cpus: '1.0'


#networks:
#  openadmin_mail_network:
#    driver: bridge



# make the data persistent
volumes:
  openadmin_mysql:
