  SERVICE:
    image: node:${SERVICE_NAME_NODE_TAG:-18-slim}
    container_name: SERVICE
    restart: always
    command: >
      sh -c "${SERVICE_NAME_NODE_REQUIREMENTS:+npm install &&} ${SERVICE_NAME_NODE_CUSTOM_CMD:-node ${SERVICE_NAME_NODE_STARTUP_FILE:-index.js}}"
    working_dir: ${SERVICE_NAME_NODE_WORKDIR:-/var/www/html/}
    stop_signal: SIGINT
    deploy:
      resources:
        limits:
          cpus: "${SERVICE_NAME_NODE_CPU:-0.1}"
          memory: "${SERVICE_NAME_NODE_RAM:-0.1G}"
          pids: 100
    volumes:
      - html_data:/var/www/html/
    networks:
      - www
