services:       
  # Webserver from 1.0.0
  caddy:
    image: ${CADDY_IMAGE}
    container_name: caddy
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/openpanel/caddy/Caddyfile:/etc/caddy/Caddyfile                           # Caddy config
      - /etc/openpanel/caddy/ssl:/data/caddy/certificates                             # Custom SSL certificates
      - /etc/openpanel/caddy/:/etc/openpanel/caddy/                                   # domain files, templates 
      - /etc/openpanel/caddy/coraza_rules.conf:/etc/openpanel/caddy/coraza_rules.conf # default rules
      - /var/log/caddy/:/var/log/caddy/
    restart: unless-stopped
    mem_limit: ${CADDY_RAM}
    cpus: ${CADDY_CPUS}
    oom_kill_disable: true
    network_mode: host

  # DNS
  bind9:
    container_name: openpanel_dns
    image: ubuntu/bind9:${BIND9_VERSION}
    environment:
      - BIND9_USER=root
      - TZ=${BIND_TIMEZONE}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /etc/bind/:/etc/bind/
    restart: unless-stopped
    mem_limit: ${BIND9_RAM}
    cpus: ${BIND9_CPUS}
    oom_kill_disable: true
    networks:
      - openpanel_network

  # FTP
  ftp_env_generator:
    image: alpine:latest
    container_name: ftp_env_generator
    volumes:
      - /etc/openpanel/ftp/:/etc/openpanel/ftp/
      - /usr/local/admin/scripts/ftp/users:/usr/local/admin/scripts/ftp/users
    entrypoint: /bin/sh -c "/usr/local/admin/scripts/ftp/users"
    restart: "no"  # only run once
    networks:
      - openpanel_network

  openadmin_ftp:
    build:
      context: /etc/openpanel/ftp/    
    container_name: openadmin_ftp
    restart: always
    ports:
      - "21:21"
      - "${FTP_PORT_RANGE}:21000-21010"
    volumes:
      - /home/:/home/
      - /etc/openpanel/ftp/vsftpd.conf:/etc/vsftpd/vsftpd.conf
      - /etc/openpanel/ftp/start_vsftpd.sh:/bin/start_vsftpd.sh
      - /etc/openpanel/ftp/vsftpd.chroot_list:/etc/vsftpd.chroot_list
      - /etc/openpanel/users/:/etc/openpanel/ftp/users/
    depends_on:
      - ftp_env_generator
    env_file:
      - /etc/openpanel/ftp/all.users
    mem_limit: ${FTP_RAM}
    cpus: ${FTP_CPUS}
    networks:
      - openpanel_network

# define custom network
networks:
  openpanel_network:
    driver: bridge
