services:
  user_service:
    image: ${docker_image}
    container_name: ${username}
    hostname: ${hostname}
    restart: unless-stopped
    ports:
      - "${port_1}"
      - "${port_2}"
      - "${port_3}"
      - "${port_4}"
      - "${port_5}"
      - "${port_6}"
    deploy:
      resources:
        limits:
          cpus: "${cpu}"
          memory: "${ram}"
    volumes:
      - /etc/openpanel/skeleton/motd:/etc/motd:ro         # SSH welcome message
      - /home/${context}/mail/:/var/mail/                 # Mail storage
      - webserver_data:/etc/${path}/                      # Nginx/Apache data
      - mysql_data:/var/lib/mysql                         # MySQL data
      - html_data:/var/www/html/                          # Website files
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  html_data:
    driver: local
  webserver_data:
    driver: local


