services:
  user_service:
    image: ${docker_image}
    container_name: ${username}
    hostname: ${hostname}
    restart: unless-stopped
    ports:
      - "${port_1}"
      - "${port_2}"
      - "${port_3}"
      - "${port_4}"
      - "${port_5}"
      - "${port_6}"
    deploy:
      resources:
        limits:
          cpus: "${cpu}"
          memory: "${ram}"
    volumes:
      - /etc/openpanel/skeleton/motd:/etc/motd:ro                                  # ssh welcome msg
      #- /etc/openpanel/nginx/default_page.html:/etc/${path}/default_page.html:ro   # default site page
    networks:
      - default

networks:
  default:
    driver: bridge
