services:
  user_service:
    image: ${docker_image}
    container_name: ${username}
    hostname: ${hostname}
    restart: unless-stopped
    ports:
      - "${port_1}"
      - "${port_2}"
      - "${port_3}"
      - "${port_4}"
      - "${port_5}"
    deploy:
      resources:
        limits:
          cpus: "${cpu}"
          memory: "${ram}"
    volumes:
      - /home/${username}/var/crons:/var/spool/cron/crontabs
      - /home/${username}:/home/${username}
      - /home/${username}/var/lib/mysql:/var/lib/mysql
      - /home/${username}/var/lib/php/sessions:/var/lib/php/sessions
      - /home/${username}/etc/${path}/sites-available:/etc/${path}/sites-available
      - /etc/openpanel/skeleton/motd:/etc/motd:ro
      - /etc/openpanel/nginx/default_page.html:/etc/${path}/default_page.html:ro
    networks:
      - default

networks:
  default:
    driver: bridge
