name: Trigger sync of conf

on:
  push:
    branches:
      - main  #always

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: Trigger Sync
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/stefanpejcic/OpenPanel/dispatches \
        -d '{"event_type":"sync-configuration"}'
