name: Update Cloudflare IPs

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Ensure that the workflow has permission to push changes

jobs:
  update_cf_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create get_cf_ips.sh script
      run: |
        mkdir -p .github/scripts
        echo '#!/bin/bash' > .github/scripts/get_cf_ips.sh
        echo 'cf_ips="$(curl -fsLm5 --retry 2 https://api.cloudflare.com/client/v4/ips)"' >> .github/scripts/get_cf_ips.sh
        echo '' >> .github/scripts/get_cf_ips.sh
        echo 'if [ -n "$cf_ips" ] && [ "$(echo "$cf_ips" | jq -r ''.success//""'')" = "true" ]; then' >> .github/scripts/get_cf_ips.sh
        echo '  cf_inc="nginx/cloudflare.inc"' >> .github/scripts/get_cf_ips.sh
        echo '' >> .github/scripts/get_cf_ips.sh
        echo '  echo "[ * ] Updating Cloudflare IP Ranges for Nginx..."' >> .github/scripts/get_cf_ips.sh
        echo '  echo "# Cloudflare IP Ranges" > $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  echo "" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  echo "# IPv4" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  for ipv4 in $(echo "$cf_ips" | jq -r ''.result.ipv4_cidrs[]//""'' | sort); do' >> .github/scripts/get_cf_ips.sh
        echo '    echo "set_real_ip_from $ipv4;" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  done' >> .github/scripts/get_cf_ips.sh
        echo '  echo "" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  echo "# IPv6" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  for ipv6 in $(echo "$cf_ips" | jq -r ''.result.ipv6_cidrs[]//""'' | sort); do' >> .github/scripts/get_cf_ips.sh
        echo '    echo "set_real_ip_from $ipv6;" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  done' >> .github/scripts/get_cf_ips.sh
        echo '  echo "" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo '  echo "real_ip_header CF-Connecting-IP;" >> $cf_inc' >> .github/scripts/get_cf_ips.sh
        echo 'fi' >> .github/scripts/get_cf_ips.sh
        chmod +x .github/scripts/get_cf_ips.sh

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Run get_cf_ips.sh
      run: .github/scripts/get_cf_ips.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add nginx/cloudflare.inc
        git commit -m "Update Cloudflare IPs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
